### ISSUE TITLE
Deprecated kwargs

### ISSUE THREAD

**Issue by zxdavb** [zxdavb/evohome#108]
```
2024-03-04 17:41:20.367 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback Actuator._handle_msg( I --- 13:237...EF0 003 00C8FF):   File "/home/dbonnes/clients/hass/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/home/dbonnes/clients/hass/homeassistant/runner.py", line 188, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/lib/python3.12/asyncio/base_events.py", line 671, in run_until_complete
    self.run_forever()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 638, in run_forever
    self._run_once()
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1963, in _run_once
    handle._run()
  File "/usr/lib/python3.12/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/home/dbonnes/clients/hass/venv/lib/python3.12/site-packages/ramses_rf/gateway.py", line 512, in _msg_handler
    process_msg(self, msg)
  File "/home/dbonnes/clients/hass/venv/lib/python3.12/site-packages/ramses_rf/dispatcher.py", line 233, in process_msg
    gwy._loop.call_soon(msg.src._handle_msg, msg)
Traceback (most recent call last):
  File "/usr/lib/python3.12/asyncio/events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "/home/dbonnes/clients/hass/venv/lib/python3.12/site-packages/ramses_rf/device/heat.py", line 156, in _handle_msg
    self._make_and_send_cmd(
  File "/home/dbonnes/clients/hass/venv/lib/python3.12/site-packages/ramses_rf/device/base.py", line 139, in _make_and_send_cmd
    super()._make_and_send_cmd(code, self.id, payload=payload, **kwargs)
  File "/home/dbonnes/clients/hass/venv/lib/python3.12/site-packages/ramses_rf/entity_base.py", line 133, in _make_and_send_cmd
    raise RuntimeError("Deprecated kwargs: %s", kwargs)
RuntimeError: ('Deprecated kwargs: %s', {'priority': <Priority.LOW: 2>})
```

**Comment by zxdavb** [comment]
Changed to: `raise RuntimeError(f"Deprecated kwargs: {kwargs} ({code}|{dest_id}|{code})")`
