### ISSUE TITLE
401 Client Error: Unauthorized for url

### ISSUE THREAD

**Issue by zxdavb** [zxdavb/evohome#11]
You may be getting this error message in your logs:
```
2018-09-16 15:09:06 DEBUG (SyncWorker_7) [custom_components.evohome] _update_state_data(): API call [1 request(s)]: client.locations[loc_idx].status()...
2018-09-16 15:09:07 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate._thuis fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/helpers/entity.py", line 224, in async_update_ha_state
    yield from self.async_device_update()
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/helpers/entity.py", line 353, in async_device_update
    yield from self.hass.async_add_job(self.update)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/etc/homeassistant/custom_components/evohome.py", line 1063, in update
    self._update_state_data(domain_data)
  File "/etc/homeassistant/custom_components/evohome.py", line 931, in _update_state_data
    client.locations[loc_idx].status()[GWS][0][TCS][0])
  File "/etc/homeassistant/deps/lib/python3.6/site-packages/evohomeclient2/location.py", line 31, in status
    r.raise_for_status()
  File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://tccna.honeywell.com/WebAPI/emea/api/v1/location/333221/status?includeTemperatureControlSystems=True
```
The key is the last line:
```
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://tccna.honeywell.com/WebAPI/emea/api/v1/location/333221/status?includeTemperatureControlSystems=True
```

Cause currently unknown - any help gratefully accepted.

**Comment by zxdavb** [comment]
@megapearl The only way I might get to the bottom of this is for a full set of logs, from HA start, until the error occurs.  Can you provide that?

Don't post it here - upload it to pastebin, or as a GIST or something similar.

**Comment by megapearl** [comment]
Okay, just restarted Homeassistant with default logger on error, and the logger of evohome component on debug, so you don't get all the warnings and other irrelevant errors from other components.
When I get back from work I'll post the entire homeassistant log to pastebin and post the url here.

**Comment by megapearl** [comment]
I see some other errors in /var/log/syslog
I don't know if these are related but...

```
Sep 17 19:58:11 ubuntu-server hass[29934]:   InsecureRequestWarning)
Sep 17 19:58:11 ubuntu-server hass[29934]: 2018-09-17 19:58:11 DEBUG (SyncWorker_23) [custom_components.evohome] _update_state_data(): API call [1 request(s)]: client.locations[loc_idx].status()...
Sep 17 19:58:11 ubuntu-server hass[29934]: 2018-09-17 19:58:11 WARNING (SyncWorker_23) [custom_components.evohome] _update_state_data(): client.locations[loc_idx].locationId = 333221
Sep 17 19:58:11 ubuntu-server hass[29934]: 2018-09-17 19:58:11 INFO (SyncWorker_23) [evohomeclient2.location] status(), calling: r = requests.get(...)...
Sep 17 19:58:12 ubuntu-server hass[29934]: /usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
Sep 17 19:58:12 ubuntu-server hass[29934]:   InsecureRequestWarning)
Sep 17 19:58:12 ubuntu-server hass[29934]: /usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
Sep 17 19:58:12 ubuntu-server hass[29934]:   InsecureRequestWarning)
Sep 17 19:58:12 ubuntu-server hass[29934]: /usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
Sep 17 19:58:12 ubuntu-server hass[29934]:   InsecureRequestWarning)
Sep 17 19:58:12 ubuntu-server hass[29934]: /usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
Sep 17 19:58:12 ubuntu-server hass[29934]:   InsecureRequestWarning)
Sep 17 19:58:12 ubuntu-server hass[29934]: /usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
Sep 17 19:58:12 ubuntu-server hass[29934]:   InsecureRequestWarning)
Sep 17 19:58:12 ubuntu-server hass[29934]: /usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
Sep 17 19:58:12 ubuntu-server hass[29934]:   InsecureRequestWarning)
Sep 17 19:58:12 ubuntu-server hass[29934]: 2018-09-17 19:58:12 INFO (SyncWorker_23) [evohomeclient2.location] status(), r.status_code: 401
Sep 17 19:58:12 ubuntu-server hass[29934]: 2018-09-17 19:58:12 INFO (SyncWorker_23) [evohomeclient2.location] status(): r.text = '[
Sep 17 19:58:12 ubuntu-server hass[29934]:   {
Sep 17 19:58:12 ubuntu-server hass[29934]:     "code": "Unauthorized",
Sep 17 19:58:12 ubuntu-server hass[29934]:     "message": "Unauthorized."
Sep 17 19:58:12 ubuntu-server hass[29934]:   }
Sep 17 19:58:12 ubuntu-server hass[29934]: ]'
Sep 17 19:58:12 ubuntu-server hass[29934]: 2018-09-17 19:58:12 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate._thuis fails
Sep 17 19:58:12 ubuntu-server hass[29934]: Traceback (most recent call last):
Sep 17 19:58:12 ubuntu-server hass[29934]:   File "/usr/local/lib/python3.6/dist-packages/homeassistant/helpers/entity.py", line 224, in async_update_ha_state
Sep 17 19:58:12 ubuntu-server hass[29934]:     yield from self.async_device_update()
Sep 17 19:58:12 ubuntu-server hass[29934]:   File "/usr/local/lib/python3.6/dist-packages/homeassistant/helpers/entity.py", line 353, in async_device_update
Sep 17 19:58:12 ubuntu-server hass[29934]:     yield from self.hass.async_add_job(self.update)
Sep 17 19:58:12 ubuntu-server hass[29934]:   File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Sep 17 19:58:12 ubuntu-server hass[29934]:     result = self.fn(*self.args, **self.kwargs)
Sep 17 19:58:12 ubuntu-server hass[29934]:   File "/etc/homeassistant/custom_components/evohome.py", line 1069, in update
Sep 17 19:58:12 ubuntu-server hass[29934]:     self._update_state_data(domain_data)
Sep 17 19:58:12 ubuntu-server hass[29934]:   File "/etc/homeassistant/custom_components/evohome.py", line 937, in _update_state_data
Sep 17 19:58:12 ubuntu-server hass[29934]:     client.locations[loc_idx].status()[GWS][0][TCS][0])
Sep 17 19:58:12 ubuntu-server hass[29934]:   File "/etc/homeassistant/deps/lib/python3.6/site-packages/evohomeclient2/location.py", line 31, in status
Sep 17 19:58:12 ubuntu-server hass[29934]:     r.raise_for_status()
Sep 17 19:58:12 ubuntu-server hass[29934]:   File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 939, in raise_for_status
Sep 17 19:58:12 ubuntu-server hass[29934]:     raise HTTPError(http_error_msg, response=self)
Sep 17 19:58:12 ubuntu-server hass[29934]: requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://tccna.honeywell.com/WebAPI/emea/api/v1/location/333221/status?includeTemperatureControlSystems=True
```

**Comment by zxdavb** [comment]
_This appeared in my inbox, but I can't find it on github - an email from @megapearl:_

>I see some other errors in /var/log/syslog
I don't know if these are related but...

```text
Sep 17 19:58:11 ubuntu-server hass[29934]:   InsecureRequestWarning)
Sep 17 19:58:11 ubuntu-server hass[29934]: 2018-09-17 19:58:11 DEBUG (SyncWorker_23) [custom_components.evohome] _update_state_data(): API call [1 request(s)]: client.locations[loc_idx].status()...
Sep 17 19:58:11 ubuntu-server hass[29934]: 2018-09-17 19:58:11 WARNING (SyncWorker_23) [custom_components.evohome] _update_state_data(): client.locations[loc_idx].locationId = 333221
Sep 17 19:58:11 ubuntu-server hass[29934]: 2018-09-17 19:58:11 INFO (SyncWorker_23) [evohomeclient2.location] status(), calling: r = requests.get(...)...
Sep 17 19:58:12 ubuntu-server hass[29934]: /usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
Sep 17 19:58:12 ubuntu-server hass[29934]:   InsecureRequestWarning)
Sep 17 19:58:12 ubuntu-server hass[29934]: /usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
Sep 17 19:58:12 ubuntu-server hass[29934]:   InsecureRequestWarning)
Sep 17 19:58:12 ubuntu-server hass[29934]: /usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
Sep 17 19:58:12 ubuntu-server hass[29934]:   InsecureRequestWarning)
Sep 17 19:58:12 ubuntu-server hass[29934]: /usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
Sep 17 19:58:12 ubuntu-server hass[29934]:   InsecureRequestWarning)
Sep 17 19:58:12 ubuntu-server hass[29934]: /usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
Sep 17 19:58:12 ubuntu-server hass[29934]:   InsecureRequestWarning)
Sep 17 19:58:12 ubuntu-server hass[29934]: /usr/local/lib/python3.6/dist-packages/urllib3/connectionpool.py:857: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
Sep 17 19:58:12 ubuntu-server hass[29934]:   InsecureRequestWarning)
Sep 17 19:58:12 ubuntu-server hass[29934]: 2018-09-17 19:58:12 INFO (SyncWorker_23) [evohomeclient2.location] status(), r.status_code: 401
Sep 17 19:58:12 ubuntu-server hass[29934]: 2018-09-17 19:58:12 INFO (SyncWorker_23) [evohomeclient2.location] status(): r.text = '[
Sep 17 19:58:12 ubuntu-server hass[29934]:   {
Sep 17 19:58:12 ubuntu-server hass[29934]:     "code": "Unauthorized",
Sep 17 19:58:12 ubuntu-server hass[29934]:     "message": "Unauthorized."
Sep 17 19:58:12 ubuntu-server hass[29934]:   }
Sep 17 19:58:12 ubuntu-server hass[29934]: ]'
Sep 17 19:58:12 ubuntu-server hass[29934]: 2018-09-17 19:58:12 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate._thuis fails
Sep 17 19:58:12 ubuntu-server hass[29934]: Traceback (most recent call last):
Sep 17 19:58:12 ubuntu-server hass[29934]:   File "/usr/local/lib/python3.6/dist-packages/homeassistant/helpers/entity.py", line 224, in async_update_ha_state
Sep 17 19:58:12 ubuntu-server hass[29934]:     yield from self.async_device_update()
Sep 17 19:58:12 ubuntu-server hass[29934]:   File "/usr/local/lib/python3.6/dist-packages/homeassistant/helpers/entity.py", line 353, in async_device_update
Sep 17 19:58:12 ubuntu-server hass[29934]:     yield from self.hass.async_add_job(self.update)
Sep 17 19:58:12 ubuntu-server hass[29934]:   File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Sep 17 19:58:12 ubuntu-server hass[29934]:     result = self.fn(*self.args, **self.kwargs)
Sep 17 19:58:12 ubuntu-server hass[29934]:   File "/etc/homeassistant/custom_components/evohome.py", line 1069, in update
Sep 17 19:58:12 ubuntu-server hass[29934]:     self._update_state_data(domain_data)
Sep 17 19:58:12 ubuntu-server hass[29934]:   File "/etc/homeassistant/custom_components/evohome.py", line 937, in _update_state_data
Sep 17 19:58:12 ubuntu-server hass[29934]:     client.locations[loc_idx].status()[GWS][0][TCS][0])
Sep 17 19:58:12 ubuntu-server hass[29934]:   File "/etc/homeassistant/deps/lib/python3.6/site-packages/evohomeclient2/location.py", line 31, in status
Sep 17 19:58:12 ubuntu-server hass[29934]:     r.raise_for_status()
Sep 17 19:58:12 ubuntu-server hass[29934]:   File "/usr/local/lib/python3.6/dist-packages/requests/models.py", line 939, in raise_for_status
Sep 17 19:58:12 ubuntu-server hass[29934]:     raise HTTPError(http_error_msg, response=self)
Sep 17 19:58:12 ubuntu-server hass[29934]: requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://tccna.honeywell.com/WebAPI/emea/api/v1/location/333221/status?includeTemperatureControlSystems=True

**Comment by zxdavb** [comment]
So, can you execute these two shell commands and post the results:
```
cat ./lib/python3.6/site-packages/evohomeclient2/location.py | grep 'def status' -A 1
```
and 
```
cat ./homeassistant/components/climate/honeywell.py | grep REQUIREMENTS
```

**Comment by zxdavb** [comment]
@megapearl I have just updated the `custom_component` so that it uses _my_ version of the **evohome-client** client api.

I have added some logging that should give us more insight.

Could you do the same logging as before, and another pastebin?  There is definitely _something_ going on...

**Comment by megapearl** [comment]
> So, can you execute these two shell commands and post the results:
> 
> ```shell
> cat ./lib/python3.6/site-packages/evohomeclient2/location.py | grep 'def status' -A 1
> ```
> 
> and
> 
> ```shell
> cat ./homeassistant/components/climate/honeywell.py | grep REQUIREMENTS
> ```
> 
> My instaint is that this is a BST/UTC problem.

I have 2 of that file on my system, I don't know which one homeassistant uses.

```
root@ubuntu-server:/etc/homeassistant# cat /etc/homeassistant/deps/lib/python3.6/site-packages/evohomeclient2/location.py | grep 'def status' -A 1
    def status(self):
        _LOGGER.info("status(), calling: r = requests.get(...)...")

root@ubuntu-server:/etc/homeassistant# cat /usr/local/lib/python3.6/dist-packages/evohomeclient2/location.py | grep 'def status' -A 1
    def status(self):
        r = requests.get('https://tccna.honeywell.com/WebAPI/emea/api/v1/location/%s/status?includeTemperatureControlSystems=True' % self.locationId, headers=self.client.headers())
```

and

```
root@ubuntu-server:/etc/homeassistant# cat /usr/local/lib/python3.6/dist-packages/homeassistant/components/climate/honeywell.py | grep REQUIREMENTS
REQUIREMENTS = ['evohomeclient==0.2.7', 'somecomfort==0.5.2']
root@ubuntu-server:/etc/homeassistant#
```

**Comment by megapearl** [comment]
> @megapearl I have just updated the `custom_component` so that it uses _my_ version of the **evohome-client** library.
> 
> I have added some logging to **evohome-client** that should give us more insight.
> 
> Could you do the same logging as before, and another pastebin? There is definitely _something_ going on...

Pulled your latest component and restarted Homeassistant.

**Comment by zxdavb** [comment]
@megapearl  You have your answer - it is also the reason why your getting SSL/HTTPS errors.

**Comment by zxdavb** [comment]
Here is the relevant bit of your logs:
```
2018-09-18 17:05:31 DEBUG (SyncWorker_30) [custom_components.evohome] _update_state_data(): API call [1 request(s)]: client.locations[loc_idx].status()...
2018-09-18 17:05:31 WARNING (SyncWorker_30) [custom_components.evohome] _update_state_data(): client.locations[loc_idx].locationId = 333221
2018-09-18 17:05:31 DEBUG (SyncWorker_30) [evohomeclient2] headers(): self.access_token = dy19Ye..., self.access_token_expires = 2018-09-18 17:05:10.660647
2018-09-18 17:05:31 DEBUG (SyncWorker_30) [evohomeclient2] headers(): datetime.now() = 2018-09-18 17:05:31.232785, self.access_token_expires - timedelta(s=30) = 2018-09-18 17:04:40.660647
2018-09-18 17:05:31 DEBUG (SyncWorker_30) [evohomeclient2] headers(): code is: 0x02
2018-09-18 17:05:31 DEBUG (SyncWorker_30) [evohomeclient2] headers(): self.access_token = g8q1t..., self.access_token_expires = 2018-09-18 17:35:30.829335
2018-09-18 17:05:31 DEBUG (SyncWorker_30) [evohomeclient2] headers(): self._headers = {'Authorization': 'bearer g8q1t3...', 'Accept': 'application/json, application/xml, text/json, text/x-json, text/javascript, text/xml'}
   ...
2018-09-18 17:05:32 WARNING (SyncWorker_30) [custom_components.evohome] self._timers = {'statusUpdated': datetime.datetime(2018, 9, 18, 17, 5, 32, 516712)}, domain_data['timers'] = {'statusUpdated': datetime.datetime(2018, 9, 18, 17, 5, 32, 516712)}
```

This time it work OK.

**Comment by megapearl** [comment]
The Ubuntu Server 18.04 is a fresh one which I installed 2 weeks ago, that's why the timezone wasn't the right one I think, I overlooked that one, never noticed the clock had an offset of -2 hours.

After I changed the timezone to Europe/Amsterdam I restarted Homeassistant again.

This log is from a couple of hours after that, seems ok to me now, or am I missing something?

http://paste.ubuntu.com/p/KbgbdVb358/

**Comment by zxdavb** [comment]
It is OK.

**Comment by megapearl** [comment]
Just pulled your component from 19 hours ago.

I see some new errors this time, I don't know if these are related to above issue, but here is the log, if you want I can make a new issue:

```
2018-09-19 17:44:12 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate._thuis fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/helpers/entity.py", line 224, in async_update_ha_state
    yield from self.async_device_update()
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/helpers/entity.py", line 353, in async_device_update
    yield from self.hass.async_add_job(self.update)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/etc/homeassistant/custom_components/evohome.py", line 1047, in update
    self._update_state_data(domain_data)
  File "/etc/homeassistant/custom_components/evohome.py", line 954, in _update_state_data
    new_dict_list = list(ec1_api.temperatures(force_refresh=True))
  File "/etc/homeassistant/deps/lib/python3.6/site-packages/evohomeclient/__init__.py", line 73, in temperatures
    self._populate_full_data(force_refresh)
  File "/etc/homeassistant/deps/lib/python3.6/site-packages/evohomeclient/__init__.py", line 42, in _populate_full_data
    self.full_data = self._convert(response.content)[0]
  File "/etc/homeassistant/deps/lib/python3.6/site-packages/evohomeclient/__init__.py", line 28, in _convert
    return json.loads(self.reader(object)[0])
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2018-09-19 17:55:20 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate._thuis fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/helpers/entity.py", line 224, in async_update_ha_state
    yield from self.async_device_update()
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/helpers/entity.py", line 353, in async_device_update
    yield from self.hass.async_add_job(self.update)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/etc/homeassistant/custom_components/evohome.py", line 1047, in update
    self._update_state_data(domain_data)
  File "/etc/homeassistant/custom_components/evohome.py", line 954, in _update_state_data
    new_dict_list = list(ec1_api.temperatures(force_refresh=True))
  File "/etc/homeassistant/deps/lib/python3.6/site-packages/evohomeclient/__init__.py", line 73, in temperatures
    self._populate_full_data(force_refresh)
  File "/etc/homeassistant/deps/lib/python3.6/site-packages/evohomeclient/__init__.py", line 42, in _populate_full_data
    self.full_data = self._convert(response.content)[0]
  File "/etc/homeassistant/deps/lib/python3.6/site-packages/evohomeclient/__init__.py", line 28, in _convert
    return json.loads(self.reader(object)[0])
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2018-09-19 18:02:27 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate._thuis fails
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/helpers/entity.py", line 224, in async_update_ha_state
    yield from self.async_device_update()
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/helpers/entity.py", line 353, in async_device_update
    yield from self.hass.async_add_job(self.update)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/etc/homeassistant/custom_components/evohome.py", line 1047, in update
    self._update_state_data(domain_data)
  File "/etc/homeassistant/custom_components/evohome.py", line 954, in _update_state_data
    new_dict_list = list(ec1_api.temperatures(force_refresh=True))
  File "/etc/homeassistant/deps/lib/python3.6/site-packages/evohomeclient/__init__.py", line 73, in temperatures
    self._populate_full_data(force_refresh)
  File "/etc/homeassistant/deps/lib/python3.6/site-packages/evohomeclient/__init__.py", line 42, in _populate_full_data
    self.full_data = self._convert(response.content)[0]
  File "/etc/homeassistant/deps/lib/python3.6/site-packages/evohomeclient/__init__.py", line 28, in _convert
    return json.loads(self.reader(object)[0])
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

**Comment by zxdavb** [comment]
@meagpearl, I can't help you with this - I can't see anything I can work with.

FWIW, the first set of errors are with v1 of the client api library (`high_precision`)- there is no exception handling there.

**Comment by megapearl** [comment]
Okay, component is working as expected, updated to latest public homeassistant v0.78.0 and no errors anymore except for the urllib3 one, I will look into that.
No issue with your component on this system anymore, so issue can be closed.

**Comment by zxdavb** [comment]
Seems an isolated issue, cause unknown. Closed.
