### ISSUE TITLE
[Fixed?] Component stopped working

### ISSUE THREAD

**Issue by Tacchi1983** [zxdavb/evohome#18]
Hi @zxdavb

I cant get the evohome custom_component to work anymore since update home assistant 0.81.2. It keeps saying config error. Is this a general problem? It works fine when i downgrade to 0.81.1. I tried several times restarting and upgrading en donwgrading and it always is stuck with 0.81.2.

```
Tue Oct 30 2018 21:07:46 GMT+0100 (Romance (standaardtijd))
Error during setup of component evohome
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.5/site-packages/homeassistant/setup.py", line 148, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/evohome.py", line 320, in setup
    load_platform(hass, 'climate', DOMAIN)
TypeError: load_platform() missing 2 required positional arguments: 'discovered' and 'hass_config'
```

**Comment by matthewcky2k** [comment]
same issue here.

**Comment by zxdavb** [comment]
OK, looking...

**Comment by zxdavb** [comment]
OK, seems to be fixed.  Code changed as per diff:
```
-    load_platform(hass, 'climate', DOMAIN)
+    load_platform(hass, 'climate', DOMAIN, {}, config)
```

(now) WorksForMe™ - I will close this issue as soon as someone confirms is now fixed for them.

**Comment by matthewcky2k** [comment]
works for me too..

**Comment by Tacchi1983** [comment]
Works perfect again. 

Thx
