### ISSUE TITLE
ConnectionError - e.g. Component Stops working after a while

### ISSUE THREAD

**Issue by matthewcky2k** [zxdavb/evohome#22]
While this seems to work fine for a few days the component seems to randomly stop working and seems it doesn't try and reconnect.  I have tried higher scan intervals but this results in the same problem

I am aware that Honeywell are doing maintenance on the platform but the component should try and reconnect from what I can tell it does not.

Using HA 85.1 using commit e745eb7 of component 

```yaml
evohome:
  username: redacted
  password: redacted
  scan_interval: 120
  high_precision: true
  use_heuristics: false
  use_schedules: false
  location_idx: 0
  away_temp: 13
```

Traceback
```
2019-01-22 16:46:41 ERROR (MainThread) [homeassistant.helpers.entity] Update for climate.ql_home fails
Traceback (most recent call last):
  File "/root/homeassistant/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/root/homeassistant/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/root/homeassistant/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/homeassistant/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/root/homeassistant/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/root/homeassistant/lib/python3.6/site-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/root/homeassistant/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/root/homeassistant/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/root/homeassistant/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/root/homeassistant/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.6/http/client.py", line 1331, in getresponse
    response.begin()
  File "/usr/lib/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.6/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/ssl.py", line 1012, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 874, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 221, in async_update_ha_state
    await self.async_device_update()
  File "/root/homeassistant/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 349, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/.homeassistant/custom_components/evohome.py", line 1079, in update
    self._update_state_data(evo_data)
  File "/root/.homeassistant/custom_components/evohome.py", line 947, in _update_state_data
    client.locations[loc_idx].status()[GWS][0][TCS][0])
  File "/root/homeassistant/lib/python3.6/site-packages/evohomeclient2/location.py", line 22, in status
    r = requests.get('https://tccna.honeywell.com/WebAPI/emea/api/v1/location/%s/status?includeTemperatureControlSystems=True' % self.locationId, headers=self.client.headers())
  File "/root/homeassistant/lib/python3.6/site-packages/evohomeclient2/__init__.py", line 89, in headers
    self._basic_login()
  File "/root/homeassistant/lib/python3.6/site-packages/evohomeclient2/__init__.py", line 67, in _basic_login
    r = requests.post(url, data=data, headers=headers)
  File "/root/homeassistant/lib/python3.6/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/root/homeassistant/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/root/homeassistant/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/homeassistant/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/root/homeassistant/lib/python3.6/site-packages/requests/adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
```

**Comment by zxdavb** [comment]
This is almost always a problem at Honeywell's end. If not, it is usually a networking issue.

The code does not process connection errors, and thus cannot/does not offer this (useful?) information...

This will change in a future version (after the rewrite)

**Comment by matthewcky2k** [comment]
Ok thanks for that info as always let me know if you need any help testing

**Comment by zxdavb** [comment]
Marked as **wontfix**, although I have improved logging to indicate is invariably a problem with Honeywell's web server infrastructure.
