### ISSUE TITLE
fan_mode errors?

### ISSUE THREAD

**Issue by megapearl** [zxdavb/evohome#4]
I'll see some new errors which I haven't seen before:

I'm also using homebridge to control the heaters via siri on iPhone, maybe that has something to do with it, I see 2 devices in each zone, a 'fan' device for which I can set a speed of 1% to 100% and a temperature device for which I can set a mode (off, heat, cool, auto) and for which I can set a temperature from (5 to 21 C)

```
2018-06-10 21:46:45 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall climate.set_fan_mode: entity_id=['climate.hallway'], fan_mode=highest>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/core.py", line 1007, in _event_to_service_call
    await service_handler.func(service_call)
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/components/climate/__init__.py", line 379, in async_fan_mode_set_service
    await climate.async_set_fan_mode(fan)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/components/climate/__init__.py", line 671, in set_fan_mode
    raise NotImplementedError()
NotImplementedError
2018-06-10 21:46:55 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall climate.set_fan_mode: entity_id=['climate.hallway'], fan_mode=medium>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/core.py", line 1007, in _event_to_service_call
    await service_handler.func(service_call)
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/components/climate/__init__.py", line 379, in async_fan_mode_set_service
    await climate.async_set_fan_mode(fan)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/components/climate/__init__.py", line 671, in set_fan_mode
    raise NotImplementedError()
NotImplementedError
2018-06-10 21:47:05 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall climate.set_fan_mode: entity_id=['climate.hallway'], fan_mode=medium>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/core.py", line 1007, in _event_to_service_call
    await service_handler.func(service_call)
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/components/climate/__init__.py", line 379, in async_fan_mode_set_service
    await climate.async_set_fan_mode(fan)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/components/climate/__init__.py", line 671, in set_fan_mode
    raise NotImplementedError()
NotImplementedError
2018-06-10 21:47:15 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall climate.set_fan_mode: entity_id=['climate.hallway'], fan_mode=high>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/core.py", line 1007, in _event_to_service_call
    await service_handler.func(service_call)
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/components/climate/__init__.py", line 379, in async_fan_mode_set_service
    await climate.async_set_fan_mode(fan)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/components/climate/__init__.py", line 671, in set_fan_mode
    raise NotImplementedError()
NotImplementedError
2018-06-10 21:47:25 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall climate.set_fan_mode: entity_id=['climate.hallway'], fan_mode=high>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/core.py", line 1007, in _event_to_service_call
    await service_handler.func(service_call)
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/components/climate/__init__.py", line 379, in async_fan_mode_set_service
    await climate.async_set_fan_mode(fan)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/components/climate/__init__.py", line 671, in set_fan_mode
    raise NotImplementedError()
NotImplementedError
2018-06-10 21:47:35 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall climate.set_fan_mode: entity_id=['climate.hallway'], fan_mode=highest>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/core.py", line 1007, in _event_to_service_call
    await service_handler.func(service_call)
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/components/climate/__init__.py", line 379, in async_fan_mode_set_service
    await climate.async_set_fan_mode(fan)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/components/climate/__init__.py", line 671, in set_fan_mode
    raise NotImplementedError()
NotImplementedError
2018-06-10 21:47:45 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall climate.set_fan_mode: entity_id=['climate.hallway'], fan_mode=medium>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/core.py", line 1007, in _event_to_service_call
    await service_handler.func(service_call)
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/components/climate/__init__.py", line 379, in async_fan_mode_set_service
    await climate.async_set_fan_mode(fan)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/components/climate/__init__.py", line 671, in set_fan_mode
    raise NotImplementedError()
NotImplementedError
2018-06-10 21:47:55 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall climate.set_fan_mode: entity_id=['climate.hallway'], fan_mode=low>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/core.py", line 1007, in _event_to_service_call
    await service_handler.func(service_call)
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/components/climate/__init__.py", line 379, in async_fan_mode_set_service
    await climate.async_set_fan_mode(fan)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/components/climate/__init__.py", line 671, in set_fan_mode
    raise NotImplementedError()
NotImplementedError
2018-06-10 22:04:37 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall climate.set_fan_mode: entity_id=['climate.kitchen'], fan_mode=medium>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/core.py", line 1007, in _event_to_service_call
    await service_handler.func(service_call)
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/components/climate/__init__.py", line 379, in async_fan_mode_set_service
    await climate.async_set_fan_mode(fan)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/components/climate/__init__.py", line 671, in set_fan_mode
    raise NotImplementedError()
NotImplementedError
2018-06-10 22:04:47 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall climate.set_fan_mode: entity_id=['climate.kitchen'], fan_mode=high>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/core.py", line 1007, in _event_to_service_call
    await service_handler.func(service_call)
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/components/climate/__init__.py", line 379, in async_fan_mode_set_service
    await climate.async_set_fan_mode(fan)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/components/climate/__init__.py", line 671, in set_fan_mode
    raise NotImplementedError()
NotImplementedError
2018-06-10 22:04:57 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall climate.set_fan_mode: entity_id=['climate.kitchen'], fan_mode=highest>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/core.py", line 1007, in _event_to_service_call
    await service_handler.func(service_call)
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/components/climate/__init__.py", line 379, in async_fan_mode_set_service
    await climate.async_set_fan_mode(fan)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/components/climate/__init__.py", line 671, in set_fan_mode
    raise NotImplementedError()
NotImplementedError
2018-06-10 22:05:07 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall climate.set_fan_mode: entity_id=['climate.kitchen'], fan_mode=highest>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/core.py", line 1007, in _event_to_service_call
    await service_handler.func(service_call)
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/components/climate/__init__.py", line 379, in async_fan_mode_set_service
    await climate.async_set_fan_mode(fan)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/components/climate/__init__.py", line 671, in set_fan_mode
    raise NotImplementedError()
NotImplementedError
2018-06-10 22:05:18 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall climate.set_fan_mode: entity_id=['climate.kitchen'], fan_mode=highest>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/core.py", line 1007, in _event_to_service_call
    await service_handler.func(service_call)
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/components/climate/__init__.py", line 379, in async_fan_mode_set_service
    await climate.async_set_fan_mode(fan)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/components/climate/__init__.py", line 671, in set_fan_mode
    raise NotImplementedError()
NotImplementedError
2018-06-10 22:05:28 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall climate.set_fan_mode: entity_id=['climate.kitchen'], fan_mode=low>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/core.py", line 1007, in _event_to_service_call
    await service_handler.func(service_call)
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/components/climate/__init__.py", line 379, in async_fan_mode_set_service
    await climate.async_set_fan_mode(fan)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/components/climate/__init__.py", line 671, in set_fan_mode
    raise NotImplementedError()
NotImplementedError
2018-06-10 22:05:38 ERROR (MainThread) [homeassistant.core] Error executing service <ServiceCall climate.set_fan_mode: entity_id=['climate.kitchen'], fan_mode=low>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/core.py", line 1007, in _event_to_service_call
    await service_handler.func(service_call)
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/components/climate/__init__.py", line 379, in async_fan_mode_set_service
    await climate.async_set_fan_mode(fan)
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/components/climate/__init__.py", line 671, in set_fan_mode
    raise NotImplementedError()
NotImplementedError


```

**Comment by zxdavb** [comment]
Hmm...

So what I see is this: for the entity `climate.hallway`, something/someone (you, via the web UI?) has made a service call: `<ServiceCall climate.set_fan_mode: entity_id=['climate.hallway'], fan_mode=highest>` and you got a `NotImplementedError`.

Which is an appropriate exception for that service call on a evohome TRV, no?  Certainly, my code does not make any explicit service calls for fans.

**Comment by megapearl** [comment]
Yes, I think that's the HOME app on ios (connected to homeassistant via homebridge).

![2018-06-10 22 30 27](https://user-images.githubusercontent.com/3420660/41206089-f0785dc0-6cfe-11e8-8610-79fcad0c920c.PNG)
![2018-06-10 22 30 58](https://user-images.githubusercontent.com/3420660/41206090-f0934e8c-6cfe-11e8-92c8-daa0a0ec7d32.PNG)
![2018-06-10 22 31 09](https://user-images.githubusercontent.com/3420660/41206091-f0ada354-6cfe-11e8-999f-5407e2899145.PNG)
![2018-06-10 22 31 25](https://user-images.githubusercontent.com/3420660/41206092-f0c6ea8a-6cfe-11e8-971a-aa49512e743f.PNG)
![2018-06-10 22 29 54](https://user-images.githubusercontent.com/3420660/41206093-f0e0540c-6cfe-11e8-8c33-78078e8679a6.PNG)

**Comment by zxdavb** [comment]
@megapearl , try not to dump too much data on this thread - makes it hard to read!

Maybe you could show me what the HA Web UI looks like?  And/or the last few lines from: `cat home-assistant.log | grep climate.hallway`

**Comment by megapearl** [comment]
I cleared it up and edited it.
HomeAssistant GUI looks like:
<img width="457" alt="inside hallway" src="https://user-images.githubusercontent.com/3420660/41206228-7282daaa-6d01-11e8-9cd8-f56dcbd9cd87.png">
<img width="285" alt="evotouch livingroom" src="https://user-images.githubusercontent.com/3420660/41206229-72a5f7ba-6d01-11e8-983d-6896e13abb81.png">
<img width="380" alt="hallway" src="https://user-images.githubusercontent.com/3420660/41206230-72bf26a4-6d01-11e8-9683-0800029ed865.png">

**Comment by zxdavb** [comment]
Well, I don't know, sorry. WFM™ (but I don't have homebridge).

**Comment by megapearl** [comment]
Ok, no problem, I'll figure that out myself, strange thing is that homebridge sees 2 devices now instead of one with the new component.
I'll keep you informed.
