### ISSUE TITLE
object of type 'int' has no len()

### ISSUE THREAD

**Issue by mazzy89** [zxdavb/evohome#41]
```
Logger: ramses_rf.protocol.command
Source: /usr/local/lib/python3.9/site-packages/ramses_rf/protocol/command.py:151
First occurred: November 27, 2021, 9:16:36 AM (120 occurrences)
Last logged: 12:01:36 AM

validate_command(): object of type 'int' has no len()
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/ramses_rf/protocol/command.py", line 143, in _wrapper
    return fcn(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/ramses_rf/protocol/command.py", line 505, in get_relay_demand
    return cls(RQ, _0008, zone_idx, dev_id, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/ramses_rf/protocol/command.py", line 267, in __init__
    self._validate(
  File "/usr/local/lib/python3.9/site-packages/ramses_rf/protocol/command.py", line 336, in _validate
    self._len = int(len(self.payload) / 2)
TypeError: object of type 'int' has no len()
````

I'm quite spammed by this error. running 0.16.20 of `evohome_cc` on Hassio

**Comment by mazzy89** [comment]
I think this commit should solve the issue. https://github.com/zxdavb/ramses_rf/commit/fb527538530265685f5df41a57b1fd02711c5e0e
please confirm if I'm wrong otherwise feel free to close it
