### ISSUE TITLE
Errors when loading component and updating devices

### ISSUE THREAD

**Issue by megapearl** [zxdavb/evohome#5]
Using latest version of your component, but have seen the error last week with the older version too.
When shutting down homeassistant for 30 minutes and start it up again is seems to work again.

edit: component not working anymore and not loading, maybe something changed at Honeywell side?
webui gives error now:
```
Invalid config
The following components and platforms could not be set up:
evohome
Please check your config.
Dismiss 
```

Last couple of days different errors in log files related to the evohome component:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/setup.py", line 146, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/etc/homeassistant/custom_components/evohome.py", line 147, in setup
    ec_api = EvohomeClient(username, password, debug=True)
  File "/etc/homeassistant/deps/lib/python3.6/site-packages/evohomeclient2/__init__.py", line 18, in __init__
    self._login()
  File "/etc/homeassistant/deps/lib/python3.6/site-packages/evohomeclient2/__init__.py", line 76, in _login
    self.installation()
  File "/etc/homeassistant/deps/lib/python3.6/site-packages/evohomeclient2/__init__.py", line 92, in installation
    self.locations.append(Location(self, loc_data))
  File "/etc/homeassistant/deps/lib/python3.6/site-packages/evohomeclient2/location.py", line 19, in __init__
    self.status()
  File "/etc/homeassistant/deps/lib/python3.6/site-packages/evohomeclient2/location.py", line 23, in status
    data = self.client._convert(r.text)
  File "/etc/homeassistant/deps/lib/python3.6/site-packages/evohomeclient2/base.py", line 32, in _convert
    return json.loads(object)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

<<SNIP>>
```

**Comment by zxdavb** [comment]
I think this is a Honeywell problem (I am using a modified client api with extra logging)...
```
2018-06-16 17:26:13 INFO (MainThread) [homeassistant.setup] Setting up evohome
2018-06-16 17:26:13 INFO (SyncWorker_7) [custom_components.evohome] Started: setup(), temp units: °C...
2018-06-16 17:26:13 INFO (SyncWorker_7) [custom_components.evohome] Connecting to the Honeywell web API now...
2018-06-16 17:26:13 INFO (SyncWorker_7) [evohomeclient2] _login(), before: r = requests.post(url, data=data, headers=headers)...
2018-06-16 17:26:13 INFO (SyncWorker_7) [evohomeclient2] _login(), after: r.status_code = 500
2018-06-16 17:26:13 ERROR (SyncWorker_7) [custom_components.evohome] Failed to connect to the Honeywell web API.
2018-06-16 17:26:13 ERROR (MainThread) [homeassistant.setup] Error during setup of component evohome
Traceback (most recent call last):
  File "/srv/hass/lib/python3.6/site-packages/homeassistant/setup.py", line 146, in _async_setup_component
    component.setup, hass, processed_config)  # type: ignore
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/root/.homeassistant/custom_components/evohome.py", line 158, in setup
    ec_api = EvohomeClient(username, password, debug=True)
  File "/srv/hass/lib/python3.6/site-packages/evohomeclient2/__init__.py", line 21, in __init__
    self._login()
  File "/srv/hass/lib/python3.6/site-packages/evohomeclient2/__init__.py", line 83, in _login
    r.raise_for_status()
  File "/srv/hass/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://tccna.honeywell.com/Auth/Error?aspxerrorpath=/Auth/OAuth/Token
2018-06-16 17:26:14 INFO (MainThread) [homeassistant.core] Bus:Handling <Event call_service[L]: domain=persistent_notification, service=create, service_data=title=Invalid config, message=The following components and platforms could not be set up:
 - [evohome](https://home-assistant.io/components/evohome/)
Please check your config., notification_id=invalid_config, service_call_id=3049064592-2>
2018-06-16 17:26:14 INFO (MainThread) [homeassistant.core] Bus:Handling <Event state_changed[L]: entity_id=persistent_notification.invalid_config, old_state=None, new_state=<state persistent_notification.invalid_config=notifying; title=Invalid config, message=The following components and platforms could not be set up:
 - [evohome](https://home-assistant.io/components/evohome/)
Please check your config. @ 2018-06-16T17:26:14.023872+01:00>>
```

**Comment by zxdavb** [comment]
OK, I've just checked.  The v1 api is working normally, but the v2 api is giving HTML 500 errors.

**Comment by zxdavb** [comment]
System now working normally.  

If anyone is curious, too many api calls should result in a 429, rather tha n a 500.
