### ISSUE TITLE
WARNING: Failed to increase precision of temperatures

### ISSUE THREAD

**Issue by megapearl** [zxdavb/evohome#7]
Hi,

Updated to the latest of your component version.
But seeing a new error, component seems to work ok.
`
2018-07-22 23:55:51 WARNING (SyncWorker_12) [custom_components.evohome] Failed to increase precision of temperatures via the v1 api.  Continuing with v2 temps.
2018-07-22 23:55:51 WARNING (MainThread) [homeassistant.loader] You are using a custom component for climate.evohome which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2018-07-22 23:55:51 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/helpers/entity_platform.py", line 326, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/helpers/entity.py", line 214, in async_update_ha_state
    attr = self.state_attributes or {}
  File "/etc/homeassistant/custom_components/evohome.py", line 1353, in state_attributes
    self.hass, self.current_temperature, self.temperature_unit,
  File "/etc/homeassistant/custom_components/evohome.py", line 1151, in current_temperature
    self._id, self._status['temperatureStatus']['temperature'])
KeyError: 'temperature'
`

**Comment by zxdavb** [comment]
Other than the precision of the reported temperatures, homeassistant should be unaffected by this error.

From the custom component's point of view:
```
WARNING: Failed to increase precision of temperatures via the v1 api. Continuing with v2 temps.
```

This is a warning, not an error. It means that the system has only been able to obtain temperatures accurate to the nearest half degree, rather than to the hundredth of a degree (although the temperatures will always be displayed to the nearest tenth of a degree).

The component usually does this by getting status via the v2 api (which it appears to have done successfully), and then placing additional calls to the version 1 API to obtain the higher precision temps.  When this fails it's simply falls back to the lower position temperatures.

Chances are that the next time the component requests higher processing temperatures (next `scan_interval`) it will work flawlessly.

Note that this has nothing much to do with startup itself, this request no different from any subsequent request (although I'm always willing to be proven wrong).

Background:
The custom component relies upon an underlying Python library (client api), called evohomeclient. 

Evohomeclient uses the requests library to pull data from Honeywell's web service.  Their web servers are notoriously unreliable, and it is not unusual to get several 503 errors per day.

Unfortunately the version of evohomeclient used by homeassistant provides very little feedback when something goes wrong, like the above, or even if invalid user credentials as supplied.

Watchforstock and I have made some changes to evohomeclient2, but not evohomeclient1, so that when HTML errors are detected (I.e.. any status code other than 200) they end up reported in the event log.

I'm hoping that this new version of the client API will be accepted into homeassistant when my PR goes through...

**Comment by zxdavb** [comment]
_Secondly_:
```
File "/etc/homeassistant/custom_components/evohome.py", line 1151, in current_temperature 
  self._id, self._status['temperatureStatus']['temperature']) KeyError: 'temperature'
```

You haven't given me enough information to make any useful comment (but a lot of the above applies), so maybe you could look earlier in the log?

**Comment by zxdavb** [comment]
Can you let me know the result of this command:
```
cat ~/.homeassistant/custom_components/evohome.py | grep REQUIRE
```

And then, if you could download the latest version, and run again?  If the error message is still there, we can do some digging...

**Comment by megapearl** [comment]
```
root@ubuntu-server:/home/donald# cat /etc/homeassistant/custom_components/evohome.py | grep REQUIRE
#REQUIREMENTS = ['https://github.com/zxdavb/evohome-client/archive/master.zip#evohomeclient==0.2.7'] # noqa
REQUIREMENTS = ['https://github.com/zxdavb/evohome-client/archive/logging.zip#evohomeclient==0.2.7'] # noqa
#REQUIREMENTS = ['evohomeclient==0.2.5']

root@ubuntu-server:/etc/homeassistant/custom_components# git pull
remote: Counting objects: 4, done.
remote: Compressing objects: 100% (1/1), done.
remote: Total 4 (delta 3), reused 4 (delta 3), pack-reused 0
Unpacking objects: 100% (4/4), done.
From https://github.com/zxdavb/evohome
   8102093..0c85dcc  master     -> origin/master
Updating 8102093..0c85dcc
Fast-forward
 README.md  |  4 ++--
 evohome.py | 33 +++++++++++++++++++--------------
 2 files changed, 21 insertions(+), 16 deletions(-)
root@ubuntu-server:/etc/homeassistant/custom_components#

root@ubuntu-server:/etc/homeassistant/custom_components# cat /etc/homeassistant/custom_components/evohome.py | grep REQUIRE
#REQUIREMENTS = ['https://github.com/zxdavb/evohome-client/archive/master.zip#evohomeclient==0.2.7'] # noqa
REQUIREMENTS = ['https://github.com/zxdavb/evohome-client/archive/logging.zip#evohomeclient==0.2.7'] # noqa
#REQUIREMENTS = ['evohomeclient==0.2.5']
root@ubuntu-server:/etc/homeassistant/custom_components#


```

**Comment by zxdavb** [comment]
OK, Interesting, especially:
```
2018-07-23 18:52:44 WARNING (MainThread) [custom_components.evohome] current_temperature(722213) - is unavailable
```

Could you search `~/.homeassistant/custom_components/evohome.py` for these two lines:
```
_LOGGER.debug("client.installation_info[idx]: %s", _tmp)
_LOGGER.debug("hass.data[DATA_EVOHOME]: %s", domain_data)
```
... and change them to:
```
_LOGGER.info("client.installation_info[idx]: %s", _tmp)
_LOGGER.info("hass.data[DATA_EVOHOME]: %s", domain_data)
```

**Comment by megapearl** [comment]
I also have in configuration.yaml:

```
# Enable debug logger:
logger:
  default: warn
  logs:
    homeassistant.custom_components.evohome: debug
```

and tried to change them to:

```
# Enable debug logger:
logger:
  default: warn
  logs:
    homeassistant.custom_components.evohome: info
```


Changed debug to info in evohome.py, no extra information in logs (not at debug and not at info), still the same:

```
2018-07-23 22:04:20 WARNING (SyncWorker_6) [custom_components.evohome] Failed to increase precision of temperatures via the v1 api.  Continuing with v2 temps.
2018-07-23 22:04:20 WARNING (MainThread) [homeassistant.loader] You are using a custom component for climate.evohome which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2018-07-23 22:04:20 WARNING (MainThread) [custom_components.evohome] current_temperature(722213) - is unavailable
2018-07-23 22:04:20 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/helpers/entity_platform.py", line 326, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/helpers/entity.py", line 214, in async_update_ha_state
    attr = self.state_attributes or {}
  File "/etc/homeassistant/custom_components/evohome.py", line 1358, in state_attributes
    self.hass, self.current_temperature, self.temperature_unit,
  File "/etc/homeassistant/custom_components/evohome.py", line 1175, in current_temperature
    self._status['temperatureStatus']['temperature'])
KeyError: 'temperature'

```

**Comment by zxdavb** [comment]
Ok let's put that one side...

How about you go to your evohome controller and see if there are any errors there.

**Comment by megapearl** [comment]
I really feel dumb now... :-(

![2018-07-23 22 45 27 low battery](https://user-images.githubusercontent.com/3420660/43102506-a1ffd47c-8ecb-11e8-8250-5092143b2753.JPG)
![2018-07-23 22 45 37 waiting for sync](https://user-images.githubusercontent.com/3420660/43102516-af1437d4-8ecb-11e8-9e4a-9743edd15912.JPG)
![2018-07-23 22 49 44 normal](https://user-images.githubusercontent.com/3420660/43102528-b43db686-8ecb-11e8-8eb8-fcf68e2d8c9e.JPG)

No errors anymore...

**Comment by zxdavb** [comment]
I knew it would be something like that ;)

The concern for me was why the code wasn't happy about it - there shouldn't have have been a traceback!

So I've made a few changes to the component, so it will be a little more graceful in future!
