### ISSUE TITLE
3150: demand at 101% (0xCA) is > 1

### ISSUE THREAD

**Issue by zxdavb** [zxdavb/evohome#71]
[Mike Henderson](https://community.home-assistant.io/u/Mike_H)
[HA Community post](https://community.home-assistant.io/t/honeywell-ch-dhw-via-rf-evohome-sundial-hometronics-chronotherm/151584/3365?u=zxdavb)

An HR92 went to 101% open this morning and generated this in the log file. I’ll force it to recalibrate, but thought I’d report the error anyway.

```
evohome_0.21.40 homeassistant_2023.1.7

Logger: ramses_rf.protocol.message
Source: /usr/local/lib/python3.10/site-packages/ramses_rf/protocol/message.py:358
First occurred: 08:30:17 (4 occurrences)
Last logged: 09:30:17

I --- 04:133367 --:------ 01:196480 3150 002 00CA < Coding error: ValueError(Invalid result: 1.01 (0xCA) is > 1)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/ramses_rf/protocol/message.py", line 331, in _validate
    result = PAYLOAD_PARSERS.get(self.code, parser_unknown)(
  File "/usr/local/lib/python3.10/site-packages/ramses_rf/protocol/parsers.py", line 140, in wrapper
    result = fnc(payload, msg, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/ramses_rf/protocol/parsers.py", line 2040, in parser_3150
    return valve_demand(payload[2:])  # TODO: check UFC/FC is == CTL/FC
  File "/usr/local/lib/python3.10/site-packages/ramses_rf/protocol/helpers.py", line 23, in wrapper
    return fnc(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/ramses_rf/protocol/helpers.py", line 318, in valve_demand
    raise ValueError(f"Invalid result: {result} (0x{value}) is > 1")
ValueError: Invalid result: 1.01 (0xCA) is > 1
```

[David Bonnes](https://community.home-assistant.io/u/zxdavb)

```python
ValueError: Invalid result: 1.01 (0xCA) is > 1

```
I have see this before… It is a puzzle to me why it gets to 101%, so I’ve not bothered to prevent the ValueError.

You can ignore this message.

[Mike Henderson](https://community.home-assistant.io/u/Mike_H)

I know it not causing me a real problem, but would that explain why some mornings in HA that actuator has reported a position of 0% when all others have shown they have opened to 100%, then that one particular actuator has then indicated a position as it starts to close?

[David Bonnes](https://community.home-assistant.io/u/zxdavb)

Not exactly.

Since the 101% packet isn’t processed, the actuator will continue to report it’s last %open, as long as it has a previous packet that has not expired.

The last %open could have been 0%, but could any value 0-100% (or 0.0 to 1.0).

If the packet has expired, then the value will be None.

Just search your packet log for 04:133367 --:------ 01:196480 3150 packets and see what payload was before the 00CA.

Just convert the 0xCA (hex) to decimal and divide by 100.

[Mike Henderson](https://community.home-assistant.io/u/Mike_H)

Yes, I can see it. This morning the actuator was at 0%, but as you say it could be another value if the temperature had dropped enough overnight. At 8.30 the schedule increases the setpoint for that zone.

```
2023-02-12T07:05:23.619465 050  I --- 04:133367 --:------ 01:196480 3150 002 0000  # 0%
2023-02-12T07:25:23.266373 050  I --- 04:133367 --:------ 01:196480 3150 002 0000  # 0%
2023-02-12T07:45:25.454516 050  I --- 04:133367 --:------ 01:196480 3150 002 0000  # 0%
2023-02-12T08:05:24.389512 050  I --- 04:133367 --:------ 01:196480 3150 002 0000  # 0%
2023-02-12T08:25:23.835755 050  I --- 04:133367 --:------ 01:196480 3150 002 0000  # 0%
2023-02-12T08:30:17.093217 050  I --- 04:133367 --:------ 01:196480 3150 002 00CA  # 101% # at 08:30am zone setpoint change from 14C to 18C
2023-02-12T08:50:14.104401 050  I --- 04:133367 --:------ 01:196480 3150 002 00CA  # 101%
2023-02-12T09:10:13.246284 050  I --- 04:133367 --:------ 01:196480 3150 002 00CA  # 101%
2023-02-12T09:30:17.669887 050  I --- 04:133367 --:------ 01:196480 3150 002 00CA  # 101%
2023-02-12T09:40:58.728457 050  I --- 04:133367 --:------ 01:196480 3150 002 00AC  # 86%
```

[David Bonnes](https://community.home-assistant.io/u/zxdavb)

Yes, I can see it. This morning the actuator was at 0%, but as you say it could be another value if the temperature had dropped enough overnight. At 8.30 the schedule increases the setpoint for that zone.

Yes, so what you’re seeing is the actuator reporting 0%, when it should really be 100%. Not ideal.

Its zone may also report incorrectly, depending on what other actuators are involved.

I guess I need to do something about it…

**Comment by zxdavb** [comment]
I am wondering is 101% is a sentinel value for something like 'max'?

Or simply an artefact of mis-calibration?

Oddly, it is the only value seen above 100% (0cC8).

**Comment by zxdavb** [comment]
A work around was added for this some months ago:
```
2023-02-12T08:30:17.093217 ...  I --- 04:133367 --:------ 01:196480 3150 002 00CA  # {'zone_idx': '00', 'heat_demand': 1.0}
```
