### ISSUE TITLE
New component not loading, while old component is loading fine.

### ISSUE THREAD

**Issue by megapearl** [zxdavb/evohome#8]
The 'old' component is loading fine (https://github.com/zxdavb/evohome/blob/master/evohome.py)
While your 'new' component isn't loading (https://raw.githubusercontent.com/zxdavb/home-assistant/dev/homeassistant/components/evohome.py)
Used your new instructions and changed the REQUIREMENTS in the honeywell.py file.

Still giving these startup errors:

```
2018-08-18 11:31:18 WARNING (SyncWorker_2) [custom_components.evohome] setup(): Calling API [4 request(s)]: client.__init__()...
2018-08-18 11:31:21 ERROR (MainThread) [homeassistant.loader] Error loading custom_components.climate.evohome. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/homeassistant/loader.py", line 94, in get_component
    module = importlib.import_module(path)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/etc/homeassistant/custom_components/climate/evohome.py", line 12, in <module>
    from homeassistant.components.evohome import (
ModuleNotFoundError: No module named 'homeassistant.components.evohome'
2018-08-18 11:31:21 ERROR (MainThread) [homeassistant.loader] Unable to find component climate.evohome
2018-08-18 11:31:21 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform climate.evohome: Platform not found.
```

**Comment by zxdavb** [comment]
It is no longer a custom component. 

  File "/etc/homeassistant/custom_components/climate/evohome.py", line 12, in <module>
    from homeassistant.components.evohome import

**Comment by zxdavb** [comment]
Having said that it may still work if you copy `evohome.py` to `.homassistant/custom_components` and `climate/evohome.py` to `.homassistant/custom_components/climate`.

**Comment by megapearl** [comment]
Problem solved by copying files to:

/usr/local/lib/python3.6/dist-packages/homeassistant/components/
and:
/usr/local/lib/python3.6/dist-packages/homeassistant/components/climate/ 

Topic Closed.
